# Generated by Django 6.0.5 on 2026-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=500)),
                ('tamaño', models.BigIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
